# Generated by Django 3.2.4 on 2021-06-06 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Семантический URL')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('meta_description', models.TextField(verbose_name='Мета описание')),
                ('meta_keywords', models.TextField(verbose_name='Мета ключевые слова')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Семантический URL')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('meta_description', models.TextField(verbose_name='Мета описание')),
                ('meta_keywords', models.TextField(verbose_name='Мета ключевые слова')),
                ('picture_for_header', models.ImageField(upload_to='uploads/posts/headers/%y/%m/%d/', verbose_name='Картинка для заголовка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
