# Generated by Django 3.2.4 on 2021-06-08 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP читателя')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='posts.post', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Количество просмотров',
                'verbose_name_plural': 'Количество просмотров',
            },
        ),
    ]
