# Generated by Django 3.2.4 on 2021-06-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта читателя'),
        ),
    ]
